#!/usr/bin/env dash

WIRELESS_DEV="wlo1"
ETHERNET_DEV="lo1"

ETH="$(ip -o link show | rg "${ETHERNET_DEV}.*state UP")"
WIFI="$(ip -o link show | rg "${WIRELESS_DEV}.*state UP"  )"

get_info(){

if [ -n "$ETH" ]; then
    echo "Ethernet"
elif [ -n "$WIFI" ]; then
    # WIFI_SSID
    iw dev $WIRELESS_DEV link | rg "SSID|signal" | cut -d: -f2 | paste -d ', ' - -
    # iw dev $WIRELESS_DEV link | rg "SSID" | cut -d: -f2
fi

}
get_icon(){

if [ -n "$ETH" ]; then
    echo "󰈀"
elif [ -n "$WIFI" ]; then

    #HAS_INTERNET
    ping -c 1 8.8.8.8 > /dev/null
    HAS_INTERNET=$?

    SIGNAL_STRENGTH=$(iw dev $WIRELESS_DEV link | rg "signal" | cut -d: -f2 | sed 's/ dBm//' )

    if [ $HAS_INTERNET -eq 0 ]; then

    if [ "$SIGNAL_STRENGTH" -ge -50 ]; then
        echo "󰤨"  # Signal Icon (Strong)
    elif [ "$SIGNAL_STRENGTH" -ge -70 ]; then
        echo "󰤥"  # Signal Icon (Medium)
    elif [ "$SIGNAL_STRENGTH" -ge -90 ]; then
        echo "󰤢"  # Signal Icon (Weak)
    else
        echo "󰤟"  # Signal Icon (Very Weak)
    fi
    else
    if [ "$SIGNAL_STRENGTH" -ge -50 ]; then
        echo "󰤩"  # Signal Icon (Strong)
    elif [ "$SIGNAL_STRENGTH" -ge -70 ]; then
        echo "󰤦"  # Signal Icon (Medium)
    elif [ "$SIGNAL_STRENGTH" -ge -90 ]; then
        echo "󰤣"  # Signal Icon (Weak)
    else
        echo "󰤠"  # Signal Icon (Very Weak)
    fi

    fi


else
    echo "󰖪"
fi

}

# if [ "$1" = "name" ]; then
#     get_info
# elif [ "$1" = "icon" ];then
#     get_icon
#
# fi

jq -n --arg info "$(get_info)" --arg icon "$(get_icon)" '{info: $info, icon: $icon}'
