#!/usr/bin/env dash

# Inferno LP 2023-08-28

windows_in(){
hyprctl clients -j | jq ".[] | select(.workspace.name == \"special:$1\" )"
}

toggle_scratchpad(){
    workspace_name="$1"
    cmd="$2"

    windows=$( windows_in "$workspace_name" )
    if [ -z "$windows" ];then
        hyprctl dispatch "exec [workspace special:$workspace_name] $cmd"
    else
        hyprctl dispatch togglespecialworkspace "$workspace_name"
    fi
}

toggle_scratchpad "$1" "$2"
