#!/usr/bin/env dash

# Inferno LP 2023-08-28
_TERMINAL="kitty"
_MUSIC_PLAYER="$_TERMINAL $SCRIPTS/music-player/mpv-music-sh"
_FILE_MANAGER="$_TERMINAL --class vifm vifm"

windows_in(){
hyprctl clients -j | jq ".[] | select(.workspace.name == \"special:$1\" )"
}

toggle_scratchpad(){
    workspace_name="$1"
    cmd="$2"

    windows=$( windows_in "$workspace_name" )
    if [ -z "$windows" ];then
        hyprctl dispatch "exec [workspace special:$workspace_name] $cmd"
    else
    hyprctl dispatch togglespecialworkspace "$workspace_name"
    fi
}

if [ "$1" = "terminal" ];then
    toggle_scratchpad "terminal" "$_TERMINAL"
elif [ "$1" = "music_player" ];then
    toggle_scratchpad "music_player" "$_MUSIC_PLAYER"
elif [ "$1" = "file_manager" ];then
    toggle_scratchpad "file_manager" "$_FILE_MANAGER"
fi
