{ config
, pkgs
, lib
, ...
}: {

  imports = [
    ./nix.nix
  ];

  wsl.defaultUser = "dev-wsl";

  virtualisation.docker = {
    enable = true;
  };
  environment.pathsToLink = [ "/share/fish" ];

  documentation = {
    dev.enable = true;
    nixos = {
      enable = true;
      includeAllModules = true;
    };
    man = {
      enable = true;
      generateCaches = true;
    };
  };
  networking.hostName = "nixosWSL"; # Define your hostname.
  networking.extraHosts = ''
        # This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
        # [network]
        # generateHosts = false
        127.0.0.1	localhost
        127.0.1.1	nixosWSL.	nixosWSL

        # The following lines are desirable for IPv6 capable hosts
        ::1     ip6-localhost ip6-loopback
        fe00::0 ip6-localnet
        ff00::0 ip6-mcastprefix
        ff02::1 ip6-allnodes
        ff02::2 ip6-allrouters
        127.0.0.1 = maestro.test serve.maestro.test react.maestro.test
  '';
  wsl.wslConf.network.generateHosts =false;
  # Set your time zone.
  time.timeZone = "Europe/Athens";

  # Select internationalisation properties.
  i18n = {
    defaultLocale = "en_US.UTF-8";
    supportedLocales = [
      "en_US.UTF-8/UTF-8"
      "el_GR.UTF-8/UTF-8"
    ];
  };

  environment.sessionVariables = {
    XDG_CACHE_HOME = "$HOME/.cache";
    XDG_CONFIG_HOME = "$HOME/.config";
    XDG_DATA_HOME = "$HOME/.local/share";
    XDG_STATE_HOME = "$HOME/.local/state";
    FLAKE_PATH = "$HOME/.nixos-config";
    EDITOR = "nvim";
    VISUAL = "nvim";
    MANPAGER = "nvim +Man!";
    # TERMINAL = "kitty";

    NIXOS_CONFIG_PATH = "$HOME/.nixos-config";

    # Home cleanup
    NODE_REPL_HISTORY = "$XDG_DATA_HOME/node_repl_history";
    PYTHONHISTFILE = "$XDG_DATA_HOME/python_history";
    CUDA_CACHE_PATH = "$XDG_CACHE_HOME/nv";
    MYSQL_HISTFILE = "$XDG_DATA_HOME/mysql_history";
    STARSHIP_CONFIG = "$XDG_CONFIG_HOME/starship/starship.toml";
  };

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users."dev-wsl" = {
    isNormalUser = true;
    extraGroups = [ "docker" "wheel" ]; # Enable ‘sudo’ for the user.
    initialPassword = "1234";

    packages = with pkgs; [

            imagemagick
      man-pages
      man-pages-posix

      miniserve

      delta
      graphviz

      wallust
      typst
      numbat

      # Shell Utils
      p7zip
      qrencode
      ast-grep

      # ffmpeg-full

      docker-compose
      jq htmlq fq
      unzip
      zip
      parallel
      file
      bc
      tealdeer
      eza
      fd
      rlwrap
      hyperfine
      python311Packages.bpython

      # System Info
      acpi
      fastfetch
      libva-utils
      pciutils

      # Media Fetch
      yt-dlp

      # Uni Notes Utils
      python311Packages.art
      socat

      ncdu
      dust
      yazi
      fswatch
      udiskie

      dash

      # Programming Utils
      shellcheck
      tokei

    ];
  };
  services.mysql = {
  enable = false;
  package = pkgs.mariadb;
};

  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [

wget
    tenki
    bottom
    libnotify
    ripgrep
    ripgrep-all
    fzf
    ripdrag

    xdg-user-dirs
    git
    pv

    xclip

    fuse-overlayfs

    (config.boot.kernelPackages.perf)
  ];

  programs.mtr.enable = true;
  programs.gnupg.agent = {
    enable = true;
    enableSSHSupport = true;
  };

  programs.fish.enable = true;
  users.defaultUserShell = pkgs.fish;

}
