#!/usr/bin/env dash

amount(){
   swaync-client -c
}
toggle_dnd(){
swaync-client --toggle-dnd
# TODO: Eww icon
eww update notification_icon_p="$(get_icon)"

}

# 󱅫 󰵙 󰂚 󰂛 󰂠
get_icon(){
icon="󰂚"
 dnd=$( swaync-client --get-dnd )
 notification_amount=$(amount)

    if [ "$dnd" = "true" ]; then
        icon="󰂠"
    elif [ "$notification_amount" -gt 0 ];then
        icon="󱅫"
    fi
    echo $icon

}
if [ "$1" = "amount" ]; then
    amount
elif [ "$1" = "icon" ]; then
    get_icon
elif [ "$1" = "dnd" ]; then
    toggle_dnd
elif [ "$1" = "open" ]; then
   swaync-client -t
fi
