#!/bin/sh

bat="/sys/class/power_supply/BAT1/"
per="$(cat "$bat/capacity")"

icon=""

status="$(cat "$bat/status")"

get_icon() {
    if [ "$status" = "Full" ]; then
        icon="󰂄"
    elif [ "$status" = "Charging" ];then

        if [ "$per" -gt "90" ]; then
            icon="󰂅"
        elif [ "$per" -gt "80" ]; then
            icon="󰂋"
        elif [ "$per" -gt "70" ]; then
            icon="󰂊"
        elif [ "$per" -gt "60" ]; then
            icon="󰢞"
        elif [ "$per" -gt "50" ]; then
            icon="󰂉"
        elif [ "$per" -gt "40" ]; then
            icon="󰢝"
        elif [ "$per" -gt "30" ]; then
            icon="󰂈"
        elif [ "$per" -gt "20" ]; then
            icon="󰂇"
        elif [ "$per" -gt "10" ]; then
            icon="󰂆"
        else
            icon="󰢜"
        fi

    else

        if [ "$per" -gt "90" ]; then
            icon="󰁹"
        elif [ "$per" -gt "80" ]; then
            icon="󰂂"
        elif [ "$per" -gt "70" ]; then
            icon="󰂁"
        elif [ "$per" -gt "60" ]; then
            icon="󰂀"
        elif [ "$per" -gt "50" ]; then
            icon="󰁿"
        elif [ "$per" -gt "40" ]; then
            icon="󰁾"
        elif [ "$per" -gt "30" ]; then
            icon="󰁽"
        elif [ "$per" -gt "20" ]; then
            icon="󰁼"
        elif [ "$per" -gt "10" ]; then
            icon="󰁼"
        elif [ "$per" -gt "0" ]; then
            icon="󰁻"
        else
            echo 󰂎 && exit
        fi
    fi
echo "$icon"
}


get_info() {
acpi -b | cut -d: -f2-
}
if [ "$1" = "-p" ]; then
    echo "$(get_icon)$(get_info)"
fi
jq -n --arg info "$(get_info)" --arg icon "$(get_icon)" '{info: $info, icon: $icon}'
